/* Data maestra: 28 partidos vigentes ante el TSE (corte 2026-09-22).
   Generada desde MAESTRO_Partidos_GT_2027.xlsx. Copia limpia en data/partidos.json.
   "accent" es el color oficial ajustado para contraste 4.5:1 sobre fondo claro. */
var DATA = [
 {
  "sig": "CABAL",
  "nombre": "Cabal",
  "afiliados": 35524,
  "color": "#1642FD",
  "colorLabel": "azul",
  "accent": "#1642FD",
  "sg": "JOSÉ ALEJANDRO CONDE SAMAYOA (secretario en funciones 22/12/2025 al 30/11/2026); LUIS FERNANDO AGUIRRE ESTRADA",
  "pres": "Roberto Arzú García-Granados",
  "presEstado": "Roberto Arzú García-Granados (precandidato)",
  "presAnunciado": true,
  "evento": "Asamblea nacional de postulación prevista (ventana oct 2026–ene 2027, TSE vía Soy502; fechas modificables)",
  "arranque": "2027-03",
  "decisor": "René Bolaños",
  "decisorCargo": "secretario de Comunicación (CEN)",
  "confianza": "alto",
  "porQue": "Secretaría de Comunicación/Propaganda del CEN; rol formal sobre imagen, propaganda y materiales de campaña.",
  "finanzas": "Delfino Taracena Godínez",
  "tel": "5481-7253",
  "telAlt": "5207-8650",
  "correo": "lorenaflores16@hotmail.com",
  "canal": "Correo formal a sede + llamada de seguimiento al teléfono TSE (mismo día o al día siguiente)",
  "sede": "4ª avenida \"A\" 13-56 zona 9",
  "zona": "Zona 9 Ciudad de Guatemala",
  "horario": null,
  "score": "A",
  "scoreRazon": "tel+correo; finanzas:Delfino Taracena Godínez; coms:René Bolaños; presidenciable; afiliados=35524",
  "orden": 1,
  "pitch": "Material promocional y merchandising de campaña (gorras, camisetas, banderas, lonas, stickers) con entrega rápida y precios por volumen para posicionar a Roberto Arzú García-Granados y la marca del partido hacia 2027.",
  "rank": 4,
  "dip": 18,
  "alc": 49,
  "deptos": 22,
  "promo2023": "alto",
  "riesgo": "bajo",
  "sancion": "desconocido",
  "web": null,
  "fb": "https://facebook.com/cabalguate/",
  "ig": null,
  "x": null,
  "tiktok": null,
  "notas": "Mejor puerta de entrada comercial: René Bolaños (Sec. Comunicación CEN). SG: Luis Fernando Aguirre / José Alejandro Conde (en funciones hasta 30/11/2026)."
 },
 {
  "sig": "ELEFANTE",
  "nombre": "Comunidad Elefante",
  "afiliados": 30790,
  "color": "#FFEF00",
  "colorLabel": "amarillo",
  "accent": "#7A7300",
  "sg": "HUGO ENRIQUE PEÑA MEDINA",
  "pres": "Hugo Enrique Peña Medina",
  "presEstado": "Hugo Enrique Peña Medina (precandidato)",
  "presAnunciado": true,
  "evento": null,
  "arranque": "2027-03",
  "decisor": "HUGO ENRIQUE PEÑA MEDINA",
  "decisorCargo": "secretario general",
  "confianza": "bajo",
  "porQue": "único contacto oficial TSE; comando de campaña aún no publicado",
  "finanzas": "Carlos Rucal",
  "tel": "5018-8435",
  "telAlt": "5715-8887",
  "correo": "evaldez@ufm.edu",
  "canal": "Correo formal a sede + llamada de seguimiento al teléfono TSE (mismo día o al día siguiente)",
  "sede": "7ª Calle 6-63 zona 2",
  "zona": "Zona 2 Ciudad de Guatemala",
  "horario": null,
  "score": "A",
  "scoreRazon": "tel+correo; finanzas:Carlos Rucal; presidenciable; afiliados=30790",
  "orden": 2,
  "pitch": "Material promocional y merchandising de campaña (gorras, camisetas, banderas, lonas, stickers) con entrega rápida y precios por volumen para posicionar a Hugo Enrique Peña Medina y la marca del partido hacia 2027.",
  "rank": 10,
  "dip": 2,
  "alc": 2,
  "deptos": null,
  "promo2023": "medio",
  "riesgo": "bajo",
  "sancion": "desconocido",
  "web": null,
  "fb": "https://www.facebook.com/ComunidadElefanteGuatemala",
  "ig": "https://www.instagram.com/comunidadelefante/",
  "x": null,
  "tiktok": null,
  "notas": "Pasada2: CEN feb-2026 con Finanzas/Organización/Actas (Liberal GT / Metropolitano / La Hora). Sin Comunicación."
 },
 {
  "sig": "VICTORIA",
  "nombre": "Victoria",
  "afiliados": 27273,
  "color": "#E11829",
  "colorLabel": "rojo",
  "accent": "#E11829",
  "sg": "EDGAR ABRAHAM RIVERA SAGASTUME",
  "pres": "Abraham Rivera",
  "presEstado": "Abraham Rivera (precandidato)",
  "presAnunciado": true,
  "evento": null,
  "arranque": "2027-03",
  "decisor": "EDGAR ABRAHAM RIVERA SAGASTUME",
  "decisorCargo": "secretario general",
  "confianza": "bajo",
  "porQue": "único contacto oficial TSE; comando de campaña aún no publicado",
  "finanzas": "Adelso Alexander Méndez Morales",
  "tel": "5289-3005",
  "telAlt": null,
  "correo": "lopezgonzalez.200615791@gmail.com",
  "canal": "Correo formal a sede + llamada de seguimiento al teléfono TSE (mismo día o al día siguiente)",
  "sede": "8va. Avenida 0-80 Zona 1, del Municipio de Mixco",
  "zona": "Zona 1 Mixco",
  "horario": null,
  "score": "A",
  "scoreRazon": "tel+correo; finanzas:Adelso Alexander Méndez Morales; presidenciable",
  "orden": 3,
  "pitch": "Material promocional y merchandising de campaña (gorras, camisetas, banderas, lonas, stickers) con entrega rápida y precios por volumen para posicionar a Abraham Rivera y la marca del partido hacia 2027.",
  "rank": 25,
  "dip": 3,
  "alc": 5,
  "deptos": null,
  "promo2023": "medio",
  "riesgo": "bajo",
  "sancion": "desconocido",
  "web": null,
  "fb": "https://www.facebook.com/PartidoVictoriaGT",
  "ig": null,
  "x": null,
  "tiktok": null,
  "notas": "Pasada2: CEN feb-2026 (La Hora). Organización vacante probable tras renuncia Cano."
 },
 {
  "sig": "RAÍCES",
  "nombre": "Raíces",
  "afiliados": 41972,
  "color": null,
  "colorLabel": null,
  "accent": "#4A617A",
  "sg": "SAMUEL ANDRES PEREZ ALVAREZ",
  "pres": null,
  "presEstado": null,
  "presAnunciado": false,
  "evento": null,
  "arranque": "2027-03",
  "decisor": "Carmen Lucía España Cosillo",
  "decisorCargo": "secretaria de Comunicación (CEN provisional)",
  "confianza": "alto",
  "porQue": "Secretaría de Comunicación/Propaganda del CEN; rol formal sobre imagen, propaganda y materiales de campaña.",
  "finanzas": "Román Wilfredo Castellanos Caal",
  "tel": "2221-3016",
  "telAlt": null,
  "correo": "info@raicesguate.gt",
  "canal": "Correo formal a sede + llamada de seguimiento al teléfono TSE (mismo día o al día siguiente)",
  "sede": "1 calle 7-68, Edificio peña, zona 1, ciudad",
  "zona": "Zona 1 Ciudad de Guatemala",
  "horario": null,
  "score": "A",
  "scoreRazon": "tel+correo; finanzas:Román Wilfredo Castellanos Caal; coms:Carmen Lucía España Cosillo; afiliados=41972",
  "orden": 4,
  "pitch": "Material promocional y merchandising de campaña (gorras, camisetas, banderas, lonas, stickers) con entrega rápida y precios por volumen; agenda previa a convocatoria electoral ene-2027.",
  "rank": 2,
  "dip": null,
  "alc": null,
  "deptos": null,
  "promo2023": "desconocido",
  "riesgo": "bajo",
  "sancion": "desconocido",
  "web": "https://raicesguate.gt",
  "fb": "https://facebook.com/raicesguate",
  "ig": "https://instagram.com/raicesguate/",
  "x": "https://x.com/raicesguate",
  "tiktok": "https://tiktok.com/@raicesguate",
  "notas": "Partido recién inscrito 07/09/2026; CEN provisional. Carmen Lucía España (Comunicación) es el contacto de materiales/imagen."
 },
 {
  "sig": "UNE",
  "nombre": "Unidad Nacional De La Esperanza",
  "afiliados": 85404,
  "color": "#50A700",
  "colorLabel": "verde",
  "accent": "#408600",
  "sg": "LOURDES TERESITA DE LEON TORRES",
  "pres": "Sandra Torres",
  "presEstado": "Sandra Torres (precandidato)",
  "presAnunciado": true,
  "evento": null,
  "arranque": "2027-03",
  "decisor": "LOURDES TERESITA DE LEON TORRES",
  "decisorCargo": "secretario general",
  "confianza": "bajo",
  "porQue": "único contacto oficial TSE; comando de campaña aún no publicado",
  "finanzas": null,
  "tel": "2309-7187",
  "telAlt": null,
  "correo": "contaune2018@hotmail.com",
  "canal": "Correo formal a sede + llamada de seguimiento al teléfono TSE (mismo día o al día siguiente)",
  "sede": "8ª. Calle 5-15 zona 9",
  "zona": "Zona 9 Ciudad de Guatemala",
  "horario": null,
  "score": "B",
  "scoreRazon": "tel+correo; web/redes; CEN amplio; presidenciable",
  "orden": 5,
  "pitch": "Material promocional y merchandising de campaña (gorras, camisetas, banderas, lonas, stickers) con entrega rápida y precios por volumen para posicionar a Sandra Torres y la marca del partido hacia 2027.",
  "rank": 1,
  "dip": 28,
  "alc": 39,
  "deptos": 22,
  "promo2023": "alto",
  "riesgo": "medio",
  "sancion": "desconocido",
  "web": null,
  "fb": "https://www.facebook.com/UNEGuatemala",
  "ig": "https://www.instagram.com/uneguatemala/",
  "x": "https://x.com/UNEGuatemala",
  "tiktok": null,
  "notas": null
 },
 {
  "sig": "SERVIR",
  "nombre": "Servir",
  "afiliados": 33107,
  "color": null,
  "colorLabel": null,
  "accent": "#4A617A",
  "sg": "CARLOS RENE PINEDA SOSA",
  "pres": "Carlos René Pineda Sosa",
  "presEstado": "Carlos René Pineda Sosa (precandidato)",
  "presAnunciado": true,
  "evento": null,
  "arranque": "2027-03",
  "decisor": "CARLOS RENE PINEDA SOSA",
  "decisorCargo": "secretario general",
  "confianza": "bajo",
  "porQue": "único contacto oficial TSE; comando de campaña aún no publicado",
  "finanzas": null,
  "tel": "3198-8329",
  "telAlt": "3198-8329",
  "correo": "info@servirgt.org",
  "canal": "Correo formal a sede + llamada de seguimiento al teléfono TSE (mismo día o al día siguiente)",
  "sede": "Oficina 902 del Edificio Spazio, 15 avenida Colonia Vista Hermosa 3, zona 15, ciudad de Guatemala",
  "zona": "Zona 15 Ciudad de Guatemala",
  "horario": null,
  "score": "B",
  "scoreRazon": "tel+correo; web/redes; presidenciable",
  "orden": 6,
  "pitch": "Material promocional y merchandising de campaña (gorras, camisetas, banderas, lonas, stickers) con entrega rápida y precios por volumen para posicionar a Carlos René Pineda Sosa y la marca del partido hacia 2027.",
  "rank": 5,
  "dip": null,
  "alc": null,
  "deptos": null,
  "promo2023": "desconocido",
  "riesgo": "bajo",
  "sancion": "desconocido",
  "web": "https://partidoservir.com",
  "fb": "https://www.facebook.com/partidopoliticoservir",
  "ig": null,
  "x": null,
  "tiktok": null,
  "notas": "Sitio oficial aporta tel 3198-8329 e info@servirgt.org además del directorio TSE. André Pozuelos es asesor sin cargo formal (no decisor de compras)."
 },
 {
  "sig": "REVOLUCION",
  "nombre": "Revolución",
  "afiliados": 31342,
  "color": null,
  "colorLabel": null,
  "accent": "#4A617A",
  "sg": "ARNOLDO FRANCISCO PÉREZ Y PÉREZ",
  "pres": "Nery Ramos",
  "presEstado": "Nery Ramos (precandidato)",
  "presAnunciado": true,
  "evento": null,
  "arranque": "2027-03",
  "decisor": "ARNOLDO FRANCISCO PÉREZ Y PÉREZ",
  "decisorCargo": "secretario general",
  "confianza": "bajo",
  "porQue": "único contacto oficial TSE; comando de campaña aún no publicado",
  "finanzas": null,
  "tel": "3769-9996",
  "telAlt": "5149-3891",
  "correo": "pprevolucion2025@gmail.com",
  "canal": "Correo formal a sede + llamada de seguimiento al teléfono TSE (mismo día o al día siguiente)",
  "sede": "7 avenida 5-45, zona 4, Edificio XP01, nivel 7, oficina 701, ciudad",
  "zona": "Zona 4 Ciudad de Guatemala",
  "horario": null,
  "score": "B",
  "scoreRazon": "tel+correo; CEN amplio; presidenciable",
  "orden": 7,
  "pitch": "Material promocional y merchandising de campaña (gorras, camisetas, banderas, lonas, stickers) con entrega rápida y precios por volumen para posicionar a Nery Ramos y la marca del partido hacia 2027.",
  "rank": 8,
  "dip": null,
  "alc": null,
  "deptos": null,
  "promo2023": "desconocido",
  "riesgo": "bajo",
  "sancion": "desconocido",
  "web": null,
  "fb": null,
  "ig": null,
  "x": null,
  "tiktok": null,
  "notas": "Prensa indica posible cambio de nombre a FIRMES; verificar nombre oficial al contactar. | Asamblea cambió a FIRMES (verificar TSE)"
 },
 {
  "sig": "NT",
  "nombre": "Nuevos Tiempos",
  "afiliados": 30946,
  "color": null,
  "colorLabel": null,
  "accent": "#4A617A",
  "sg": "SHIRLEY JOANNA RIVERA ZALDAÑA",
  "pres": "Sandra Jovel Polanco",
  "presEstado": "Sandra Jovel Polanco (virtual NT, La Hora 10/09/2026)",
  "presAnunciado": true,
  "evento": null,
  "arranque": "2027-03",
  "decisor": "SHIRLEY JOANNA RIVERA ZALDAÑA",
  "decisorCargo": "secretario general",
  "confianza": "bajo",
  "porQue": "único contacto oficial TSE; comando de campaña aún no publicado",
  "finanzas": null,
  "tel": "4500-0097",
  "telAlt": "4500-0097",
  "correo": "nuevostiemposguate@hotmail.com",
  "canal": "Correo formal a sede + llamada de seguimiento al teléfono TSE (mismo día o al día siguiente)",
  "sede": "10 avenida 18-02 zona 10, Centro Comercial Prisa, Of. 201 C, 2º. Nivel, ciudad de Guatemala",
  "zona": "Zona 10 Ciudad de Guatemala",
  "horario": null,
  "score": "B",
  "scoreRazon": "tel+correo; web/redes; presidenciable",
  "orden": 8,
  "pitch": "Material promocional y merchandising de campaña (gorras, camisetas, banderas, lonas, stickers) con entrega rápida y precios por volumen para posicionar a Sandra Jovel Polanco y la marca del partido hacia 2027.",
  "rank": 9,
  "dip": null,
  "alc": null,
  "deptos": null,
  "promo2023": "desconocido",
  "riesgo": "bajo",
  "sancion": "desconocido",
  "web": null,
  "fb": "https://www.facebook.com/NuevosTiemposGuatemala",
  "ig": "https://www.instagram.com/nuevostiemposgt",
  "x": null,
  "tiktok": null,
  "notas": "Pasada3: FB oficial About tel 4500-0097 + IG nuevostiemposgt. Azmitia no reconfirmado como jefe campaña NT."
 },
 {
  "sig": "AZUL",
  "nombre": "Azul",
  "afiliados": 30575,
  "color": "#1F21AA",
  "colorLabel": "azul",
  "accent": "#1F21AA",
  "sg": "JORGE MARIO VILLAGRÁN ALVAREZ",
  "pres": "Giovanni Efraín Reyes Ortiz",
  "presEstado": "Giovanni Efraín Reyes Ortiz (precandidato)",
  "presAnunciado": true,
  "evento": "Asamblea nacional de postulación prevista (ventana oct 2026–ene 2027, TSE vía Soy502; fechas modificables)",
  "arranque": "2027-03",
  "decisor": "JORGE MARIO VILLAGRÁN ALVAREZ",
  "decisorCargo": "secretario general",
  "confianza": "bajo",
  "porQue": "único contacto oficial TSE; comando de campaña aún no publicado",
  "finanzas": null,
  "tel": "54695251",
  "telAlt": null,
  "correo": "mmonterroso621@gmail.com",
  "canal": "Correo formal a sede + llamada de seguimiento al teléfono TSE (mismo día o al día siguiente)",
  "sede": "11 calle 8-14 zona 1, Edificio Tecun, quinto nivel, oficina 51",
  "zona": "Zona 1 Ciudad de Guatemala",
  "horario": null,
  "score": "B",
  "scoreRazon": "tel+correo; web/redes; presidenciable",
  "orden": 9,
  "pitch": "Material promocional y merchandising de campaña (gorras, camisetas, banderas, lonas, stickers) con entrega rápida y precios por volumen para posicionar a Giovanni Efraín Reyes Ortiz y la marca del partido hacia 2027.",
  "rank": 11,
  "dip": 2,
  "alc": 2,
  "deptos": null,
  "promo2023": "medio",
  "riesgo": "bajo",
  "sancion": "desconocido",
  "web": null,
  "fb": "https://www.facebook.com/p/Partido-Azul-100063929476257/",
  "ig": null,
  "x": null,
  "tiktok": null,
  "notas": "Pasada2: FB oficial documentado; About sin tel/email."
 },
 {
  "sig": "JAGUAR",
  "nombre": "Jaguar",
  "afiliados": 30005,
  "color": null,
  "colorLabel": null,
  "accent": "#4A617A",
  "sg": "ANTHONY SEGURA FRANCO",
  "pres": "Óscar Ruperto Cruz Oliva",
  "presEstado": "Óscar Ruperto Cruz Oliva (precandidato)",
  "presAnunciado": true,
  "evento": "Asamblea nacional extraordinaria programada 29 nov 2026 (Soy502)",
  "arranque": "2027-03",
  "decisor": "ANTHONY SEGURA FRANCO",
  "decisorCargo": "secretario general",
  "confianza": "bajo",
  "porQue": "único contacto oficial TSE; comando de campaña aún no publicado",
  "finanzas": null,
  "tel": "3201-4513",
  "telAlt": "4596-7559",
  "correo": "jaguarbalam.guatemala@gmail.com",
  "canal": "Correo formal a sede + llamada de seguimiento al teléfono TSE (mismo día o al día siguiente)",
  "sede": "11 avenida Final 10-91 Condominio Villas El Roble I Casa Numero 6 Zona 11 Las Charcas",
  "zona": "Zona 11 Ciudad de Guatemala",
  "horario": null,
  "score": "B",
  "scoreRazon": "tel+correo; web/redes; presidenciable",
  "orden": 10,
  "pitch": "Material promocional y merchandising de campaña (gorras, camisetas, banderas, lonas, stickers) con entrega rápida y precios por volumen para posicionar a Óscar Ruperto Cruz Oliva y la marca del partido hacia 2027.",
  "rank": 13,
  "dip": null,
  "alc": null,
  "deptos": null,
  "promo2023": "desconocido",
  "riesgo": "bajo",
  "sancion": "desconocido",
  "web": null,
  "fb": "https://www.facebook.com/partidojaguar",
  "ig": null,
  "x": null,
  "tiktok": null,
  "notas": null
 },
 {
  "sig": "UNIONISTA",
  "nombre": "Partido Unionista",
  "afiliados": 29893,
  "color": "#1F6592",
  "colorLabel": "azul",
  "accent": "#1F6592",
  "sg": "SEBASTIAN SIERO ASTURIAS",
  "pres": "Zury Ríos Sosa",
  "presEstado": "Zury Ríos Sosa (precandidato)",
  "presAnunciado": true,
  "evento": "Asamblea nacional de postulación prevista (ventana oct 2026–ene 2027, TSE vía Soy502; fechas modificables)",
  "arranque": "2027-03",
  "decisor": "SEBASTIAN SIERO ASTURIAS",
  "decisorCargo": "secretario general",
  "confianza": "bajo",
  "porQue": "único contacto oficial TSE; comando de campaña aún no publicado",
  "finanzas": null,
  "tel": "23625945",
  "telAlt": "57521944",
  "correo": "juridicayelectoralunionista@hotmail.es",
  "canal": "Correo formal a sede + llamada de seguimiento al teléfono TSE (mismo día o al día siguiente)",
  "sede": "1ra. Avenida 3-30 Zona 10, Segundo Nivel Oficina 1",
  "zona": "Zona 10 Ciudad de Guatemala",
  "horario": null,
  "score": "B",
  "scoreRazon": "tel+correo; web/redes; CEN amplio; presidenciable",
  "orden": 11,
  "pitch": "Material promocional y merchandising de campaña (gorras, camisetas, banderas, lonas, stickers) con entrega rápida y precios por volumen para posicionar a Zury Ríos Sosa y la marca del partido hacia 2027.",
  "rank": 14,
  "dip": null,
  "alc": 2,
  "deptos": null,
  "promo2023": "medio",
  "riesgo": "bajo",
  "sancion": "desconocido",
  "web": null,
  "fb": "https://www.facebook.com/unionista",
  "ig": "https://www.instagram.com/partido_unionista/",
  "x": null,
  "tiktok": null,
  "notas": null
 },
 {
  "sig": "PPN",
  "nombre": "Partido Politico Nosotros",
  "afiliados": 29872,
  "color": "#CF152C",
  "colorLabel": "rojo",
  "accent": "#CF152C",
  "sg": "RUDY GUZMÁN",
  "pres": "David Napoleón Barrientos Girón",
  "presEstado": "David Napoleón Barrientos Girón (precandidato)",
  "presAnunciado": true,
  "evento": null,
  "arranque": "2027-03",
  "decisor": "RUDY GUZMÁN",
  "decisorCargo": "secretario general",
  "confianza": "bajo",
  "porQue": "único contacto oficial TSE; comando de campaña aún no publicado",
  "finanzas": null,
  "tel": "54887636",
  "telAlt": "25092855",
  "correo": "nosotros.ppn@gmail.com",
  "canal": "Correo formal a sede + llamada de seguimiento al teléfono TSE (mismo día o al día siguiente)",
  "sede": "0 avenida \"A\" 9-61 zona 9",
  "zona": "Zona 9 Ciudad de Guatemala",
  "horario": null,
  "score": "B",
  "scoreRazon": "tel+correo; web/redes; presidenciable",
  "orden": 12,
  "pitch": "Material promocional y merchandising de campaña (gorras, camisetas, banderas, lonas, stickers) con entrega rápida y precios por volumen para posicionar a David Napoleón Barrientos Girón y la marca del partido hacia 2027.",
  "rank": 15,
  "dip": 3,
  "alc": 10,
  "deptos": null,
  "promo2023": "medio",
  "riesgo": "bajo",
  "sancion": "desconocido",
  "web": null,
  "fb": "https://www.facebook.com/partidonosotros",
  "ig": null,
  "x": null,
  "tiktok": null,
  "notas": null
 },
 {
  "sig": "VIVA",
  "nombre": "Visión Con Valores",
  "afiliados": 29133,
  "color": "#00A3E6",
  "colorLabel": "celeste",
  "accent": "#007CAF",
  "sg": "ROBERTO RODRIGO ARMANDO CASTILLO BARRIENTOS",
  "pres": "Armando Castillo",
  "presEstado": "Armando Castillo (precandidato)",
  "presAnunciado": true,
  "evento": "Asamblea nacional de postulación prevista (ventana oct 2026–ene 2027, TSE vía Soy502; fechas modificables)",
  "arranque": "2027-03",
  "decisor": "ROBERTO RODRIGO ARMANDO CASTILLO BARRIENTOS",
  "decisorCargo": "secretario general",
  "confianza": "bajo",
  "porQue": "único contacto oficial TSE; comando de campaña aún no publicado",
  "finanzas": null,
  "tel": "2220-1585",
  "telAlt": null,
  "correo": "generalviva@viva.gt",
  "canal": "Correo formal a sede + llamada de seguimiento al teléfono TSE (mismo día o al día siguiente)",
  "sede": "8ª. Avenida 12-29 zona 1 Oficina 301, Tercer Nivel Edificio Espinoza Castañeda",
  "zona": "Zona 1 Ciudad de Guatemala",
  "horario": null,
  "score": "B",
  "scoreRazon": "tel+correo; web/redes; presidenciable",
  "orden": 13,
  "pitch": "Material promocional y merchandising de campaña (gorras, camisetas, banderas, lonas, stickers) con entrega rápida y precios por volumen para posicionar a Armando Castillo y la marca del partido hacia 2027.",
  "rank": 16,
  "dip": 11,
  "alc": 9,
  "deptos": null,
  "promo2023": "alto",
  "riesgo": "alto",
  "sancion": "si",
  "web": "https://viva.gt",
  "fb": "https://facebook.com/visionconvalores.VIVA",
  "ig": "https://instagram.com/partidovivagt/",
  "x": "https://x.com/PartidoVivaGua",
  "tiktok": "https://tiktok.com/@partidovivaoficial",
  "notas": null
 },
 {
  "sig": "TODOS",
  "nombre": "Todos",
  "afiliados": 29042,
  "color": "#652D91",
  "colorLabel": "morado",
  "accent": "#652D91",
  "sg": "BYRON BLADIMIRO RODRIGUEZ PALACIOS",
  "pres": "Sergio Madrazo",
  "presEstado": "Sergio Madrazo (precandidato)",
  "presAnunciado": true,
  "evento": null,
  "arranque": "2027-03",
  "decisor": "BYRON BLADIMIRO RODRIGUEZ PALACIOS",
  "decisorCargo": "secretario general",
  "confianza": "bajo",
  "porQue": "único contacto oficial TSE; comando de campaña aún no publicado",
  "finanzas": null,
  "tel": "4632-7082",
  "telAlt": null,
  "correo": "info@todos.gt",
  "canal": "Correo formal a sede + llamada de seguimiento al teléfono TSE (mismo día o al día siguiente)",
  "sede": "Boulevard Liberación 15-86 Zona 13 Edificio Obelisco Of. 308, Guatemala",
  "zona": "Zona 13 Ciudad de Guatemala",
  "horario": null,
  "score": "B",
  "scoreRazon": "tel+correo; web/redes; presidenciable",
  "orden": 14,
  "pitch": "Material promocional y merchandising de campaña (gorras, camisetas, banderas, lonas, stickers) con entrega rápida y precios por volumen para posicionar a Sergio Madrazo y la marca del partido hacia 2027.",
  "rank": 17,
  "dip": 6,
  "alc": 15,
  "deptos": null,
  "promo2023": "medio",
  "riesgo": "bajo",
  "sancion": "desconocido",
  "web": "https://todos.gt",
  "fb": "https://facebook.com/todosnac/",
  "ig": "https://instagram.com/partidotodos",
  "x": "https://x.com/TODOSXGT",
  "tiktok": null,
  "notas": null
 },
 {
  "sig": "CAMBIO",
  "nombre": "Cambio",
  "afiliados": 28920,
  "color": "#FBD504",
  "colorLabel": "amarillo",
  "accent": "#836F02",
  "sg": "JORGE EDUARDO BALDIZON VARGAS",
  "pres": "Isaac Farchi",
  "presEstado": "Isaac Farchi (precandidato)",
  "presAnunciado": true,
  "evento": "Asamblea nacional de postulación prevista (ventana oct 2026–ene 2027, TSE vía Soy502; fechas modificables)",
  "arranque": "2027-03",
  "decisor": "JORGE EDUARDO BALDIZON VARGAS",
  "decisorCargo": "secretario general",
  "confianza": "bajo",
  "porQue": "único contacto oficial TSE; comando de campaña aún no publicado",
  "finanzas": null,
  "tel": "2508-7714",
  "telAlt": null,
  "correo": "partidopoliticocambio@gmail.com",
  "canal": "Correo formal a sede + llamada de seguimiento al teléfono TSE (mismo día o al día siguiente)",
  "sede": "Avenida Reforma 13-70 zona 9, Edificio Real Reforma, 4º. Nivel, oficina 4C, ciudad de Guatemala",
  "zona": "Zona 9 Ciudad de Guatemala",
  "horario": null,
  "score": "B",
  "scoreRazon": "tel+correo; web/redes; presidenciable",
  "orden": 15,
  "pitch": "Material promocional y merchandising de campaña (gorras, camisetas, banderas, lonas, stickers) con entrega rápida y precios por volumen para posicionar a Isaac Farchi y la marca del partido hacia 2027.",
  "rank": 18,
  "dip": 1,
  "alc": 5,
  "deptos": null,
  "promo2023": "medio",
  "riesgo": "bajo",
  "sancion": "desconocido",
  "web": null,
  "fb": "https://www.facebook.com/partidocambiogt/",
  "ig": null,
  "x": null,
  "tiktok": null,
  "notas": null
 },
 {
  "sig": "CREO",
  "nombre": "Compromiso, Renovacion Y Orden",
  "afiliados": 28743,
  "color": "#FFCF00",
  "colorLabel": "amarillo",
  "accent": "#8F7400",
  "sg": "RAFAEL ERNESTO DIAZ AITKENHEAD",
  "pres": "Neto Bran (Ernesto Guillermo Bran Montenegro)",
  "presEstado": "Neto Bran (Ernesto Guillermo Bran Montenegro) (anunciado_prensa)",
  "presAnunciado": true,
  "evento": "Asamblea proclamación binomio (Neto Bran) — fiscal Andrés Galindo: hasta 20 nov 2026 (antes convocada 20 sep 2026)",
  "arranque": "2026-11",
  "decisor": "RAFAEL ERNESTO DIAZ AITKENHEAD",
  "decisorCargo": "secretario general",
  "confianza": "bajo",
  "porQue": "único contacto oficial TSE; comando de campaña aún no publicado",
  "finanzas": null,
  "tel": "47509993",
  "telAlt": null,
  "correo": "Gpartidopoliticocreo@gmail.com",
  "canal": "Correo formal a sede + llamada de seguimiento al teléfono TSE (mismo día o al día siguiente)",
  "sede": "2ª Calle 7-79 zona 9 Edificio Nova Reformador Oficina 1315",
  "zona": "Zona 9 Ciudad de Guatemala",
  "horario": null,
  "score": "B",
  "scoreRazon": "tel+correo; web/redes; CEN amplio; presidenciable",
  "orden": 16,
  "pitch": "Material promocional y merchandising de campaña (gorras, camisetas, banderas, lonas, stickers) con entrega rápida y precios por volumen para posicionar a Neto Bran y la marca del partido hacia 2027.",
  "rank": 19,
  "dip": 3,
  "alc": 3,
  "deptos": null,
  "promo2023": "medio",
  "riesgo": "medio",
  "sancion": "si",
  "web": null,
  "fb": "https://www.facebook.com/PartidoCreo/",
  "ig": "https://www.instagram.com/partidocreo/",
  "x": null,
  "tiktok": null,
  "notas": "Pasada2: CEN nov-2025 (Metropolitano). Proclamación Bran convocada 20/09/2026; sin jefe campaña."
 },
 {
  "sig": "VALOR",
  "nombre": "Valor",
  "afiliados": 28521,
  "color": "#1898A1",
  "colorLabel": "celeste/teal",
  "accent": "#148087",
  "sg": "ELMER JOSUE PALENCIA REYES",
  "pres": "Fausto Arimany",
  "presEstado": "Fausto Arimany (precandidato)",
  "presAnunciado": true,
  "evento": "Asamblea nacional de postulación prevista (ventana oct 2026–ene 2027, TSE vía Soy502; fechas modificables)",
  "arranque": "2027-03",
  "decisor": "ELMER JOSUE PALENCIA REYES",
  "decisorCargo": "secretario general",
  "confianza": "bajo",
  "porQue": "único contacto oficial TSE; comando de campaña aún no publicado",
  "finanzas": null,
  "tel": "3024-5648",
  "telAlt": null,
  "correo": "partidopoliticovalor@gmail.com",
  "canal": "Correo formal a sede + llamada de seguimiento al teléfono TSE (mismo día o al día siguiente)",
  "sede": "6 Avenida 1-00 zona 2",
  "zona": "Zona 2 Ciudad de Guatemala",
  "horario": null,
  "score": "B",
  "scoreRazon": "tel+correo; web/redes; presidenciable",
  "orden": 17,
  "pitch": "Material promocional y merchandising de campaña (gorras, camisetas, banderas, lonas, stickers) con entrega rápida y precios por volumen para posicionar a Fausto Arimany y la marca del partido hacia 2027.",
  "rank": 21,
  "dip": 5,
  "alc": 14,
  "deptos": null,
  "promo2023": "alto",
  "riesgo": "bajo",
  "sancion": "desconocido",
  "web": null,
  "fb": "https://www.facebook.com/PartidoValor",
  "ig": "https://www.instagram.com/partidovalor/",
  "x": "https://x.com/PartidoValor",
  "tiktok": null,
  "notas": "SG Palencia declaró (Con Criterio 2026-07-17) que aún no tienen estratega; timing de compra de promo puede retrasarse hasta definir candidato."
 },
 {
  "sig": "VAMOS",
  "nombre": "Vamos Por Una Guatemala Diferente",
  "afiliados": 41050,
  "color": "#34478E",
  "colorLabel": "azul cobalto",
  "accent": "#34478E",
  "sg": "LUIS ALBERTO RODRIGUEZ REYES",
  "pres": null,
  "presEstado": null,
  "presAnunciado": false,
  "evento": null,
  "arranque": "2027-03",
  "decisor": "LUIS ALBERTO RODRIGUEZ REYES",
  "decisorCargo": "secretario general",
  "confianza": "bajo",
  "porQue": "único contacto oficial TSE; comando de campaña aún no publicado",
  "finanzas": null,
  "tel": "2339-1165",
  "telAlt": null,
  "correo": "vamosguatemalagt@gmail.com",
  "canal": "Correo formal a sede + llamada de seguimiento al teléfono TSE (mismo día o al día siguiente)",
  "sede": "4ª. Calle A 1-23 zona 3 Ciudad",
  "zona": "Zona 3 Ciudad de Guatemala",
  "horario": null,
  "score": "B",
  "scoreRazon": "tel+correo; web/redes",
  "orden": 18,
  "pitch": "Material promocional y merchandising de campaña (gorras, camisetas, banderas, lonas, stickers) con entrega rápida y precios por volumen para afiliación territorial y arranque preelectoral 2027.",
  "rank": 3,
  "dip": 39,
  "alc": 132,
  "deptos": 22,
  "promo2023": "alto",
  "riesgo": "medio",
  "sancion": "desconocido",
  "web": null,
  "fb": "https://www.facebook.com/PartidoVamos",
  "ig": "https://instagram.com/partidovamosgt",
  "x": "https://x.com/PartidoVamosGt",
  "tiktok": null,
  "notas": null
 },
 {
  "sig": "VOS",
  "nombre": "Voluntad, Oportunidad Y Solidaridad",
  "afiliados": 31670,
  "color": "#D0147E",
  "colorLabel": "magenta",
  "accent": "#D0147E",
  "sg": "JAIRO JOAQUIN FLORES DIVAS",
  "pres": null,
  "presEstado": null,
  "presAnunciado": false,
  "evento": null,
  "arranque": "2027-03",
  "decisor": "JAIRO JOAQUIN FLORES DIVAS",
  "decisorCargo": "secretario general",
  "confianza": "bajo",
  "porQue": "único contacto oficial TSE; comando de campaña aún no publicado",
  "finanzas": null,
  "tel": "5476-8747",
  "telAlt": null,
  "correo": "secretariageneral@partidovos.com",
  "canal": "Correo formal a sede + llamada de seguimiento al teléfono TSE (mismo día o al día siguiente)",
  "sede": "13 calle 2-63 zona 1 ciudad",
  "zona": "Zona 1 Ciudad de Guatemala",
  "horario": null,
  "score": "B",
  "scoreRazon": "tel+correo; web/redes; CEN amplio",
  "orden": 19,
  "pitch": "Material promocional y merchandising de campaña (gorras, camisetas, banderas, lonas, stickers) con entrega rápida y precios por volumen para afiliación territorial y arranque preelectoral 2027.",
  "rank": 7,
  "dip": 4,
  "alc": 1,
  "deptos": null,
  "promo2023": "medio",
  "riesgo": "alto",
  "sancion": "si",
  "web": "http://partidovos.com",
  "fb": "https://facebook.com/VOSPartidoPolitico/",
  "ig": null,
  "x": null,
  "tiktok": null,
  "notas": "Pasada2: CEN dic-2025 (Prensa Libre). Sin Comunicación. Pasada3: Dávila ahora en XG."
 },
 {
  "sig": "FG",
  "nombre": "Fuerza Por Guatemala",
  "afiliados": 30207,
  "color": null,
  "colorLabel": null,
  "accent": "#4A617A",
  "sg": "JOSE MAURICIO RADFORD HERNANDEZ",
  "pres": null,
  "presEstado": null,
  "presAnunciado": false,
  "evento": null,
  "arranque": "2027-03",
  "decisor": "JOSE MAURICIO RADFORD HERNANDEZ",
  "decisorCargo": "secretario general",
  "confianza": "bajo",
  "porQue": "único contacto oficial TSE; comando de campaña aún no publicado",
  "finanzas": null,
  "tel": "2314-1717",
  "telAlt": "2314-1717",
  "correo": "informacion@fuerzaporguatemala.org.gt",
  "canal": "Correo formal a informacion@fuerzaporguatemala.org.gt + llamada 2314-1717 o 5697-5009",
  "sede": "Avenida Hincapié 3-49 zona 13 ciudad de Guatemala",
  "zona": "Zona 13 Ciudad de Guatemala",
  "horario": null,
  "score": "B",
  "scoreRazon": "tel+correo; web/redes; CEN amplio",
  "orden": 20,
  "pitch": "Material promocional y merchandising de campaña (gorras, camisetas, banderas, lonas, stickers) con entrega rápida y precios por volumen para afiliación territorial y arranque preelectoral 2027.",
  "rank": 12,
  "dip": null,
  "alc": null,
  "deptos": null,
  "promo2023": "desconocido",
  "riesgo": "bajo",
  "sancion": "desconocido",
  "web": "https://fuerzaporguatemala.org.gt",
  "fb": "https://www.facebook.com/fuerzaporguatemala",
  "ig": "https://www.instagram.com/fuerzaporguatemala/",
  "x": null,
  "tiktok": null,
  "notas": "Sin correo en LPP TSE; solo teléfono sede."
 },
 {
  "sig": "BIEN",
  "nombre": "Bienestar Nacional",
  "afiliados": 28531,
  "color": "#E78C35",
  "colorLabel": "naranja",
  "accent": "#A66526",
  "sg": "FIDEL REYES RODRIGUEZ",
  "pres": null,
  "presEstado": null,
  "presAnunciado": false,
  "evento": null,
  "arranque": "2027-03",
  "decisor": "FIDEL REYES RODRIGUEZ",
  "decisorCargo": "secretario general",
  "confianza": "bajo",
  "porQue": "único contacto oficial TSE; comando de campaña aún no publicado",
  "finanzas": null,
  "tel": "2254-3653",
  "telAlt": null,
  "correo": "ppbienestarnacional@gmail.com",
  "canal": "Correo formal a sede + llamada de seguimiento al teléfono TSE (mismo día o al día siguiente)",
  "sede": "8ª. Avenida 6-30 Zona 2",
  "zona": "Zona 2 Ciudad de Guatemala",
  "horario": null,
  "score": "B",
  "scoreRazon": "tel+correo; web/redes",
  "orden": 21,
  "pitch": "Material promocional y merchandising de campaña (gorras, camisetas, banderas, lonas, stickers) con entrega rápida y precios por volumen para afiliación territorial y arranque preelectoral 2027.",
  "rank": 20,
  "dip": 4,
  "alc": 6,
  "deptos": null,
  "promo2023": "medio",
  "riesgo": "bajo",
  "sancion": "desconocido",
  "web": "https://bien.gt",
  "fb": "https://www.facebook.com/BIENGuatemala/",
  "ig": null,
  "x": null,
  "tiktok": null,
  "notas": null
 },
 {
  "sig": "WINAQ",
  "nombre": "Movimiento Político Winaq",
  "afiliados": 28197,
  "color": "#E15D27",
  "colorLabel": "naranja",
  "accent": "#C65222",
  "sg": "AMILCAR DE JESUS POP AC",
  "pres": null,
  "presEstado": null,
  "presAnunciado": false,
  "evento": null,
  "arranque": "2027-03",
  "decisor": "AMILCAR DE JESUS POP AC",
  "decisorCargo": "secretario general",
  "confianza": "bajo",
  "porQue": "único contacto oficial TSE; comando de campaña aún no publicado",
  "finanzas": null,
  "tel": "3926-5691",
  "telAlt": "3926-5691",
  "correo": "info@winaq.org",
  "canal": "Correo formal a sede + llamada de seguimiento al teléfono TSE (mismo día o al día siguiente)",
  "sede": "4ª. Calle \"A\" 0-28 zona 1 Ciudad",
  "zona": "Zona 1 Ciudad de Guatemala",
  "horario": "8:00 AM – 4:00 PM",
  "score": "B",
  "scoreRazon": "tel+correo; web/redes",
  "orden": 22,
  "pitch": "Material promocional y merchandising de campaña (gorras, camisetas, banderas, lonas, stickers) con entrega rápida y precios por volumen para afiliación territorial y arranque preelectoral 2027.",
  "rank": 22,
  "dip": null,
  "alc": 1,
  "deptos": null,
  "promo2023": "bajo",
  "riesgo": "bajo",
  "sancion": "desconocido",
  "web": "https://winaq.org",
  "fb": "https://facebook.com/MovimientoWINAQ",
  "ig": "https://instagram.com/movimientowinaq",
  "x": "https://x.com/movimientowinaq",
  "tiktok": null,
  "notas": null
 },
 {
  "sig": "PV",
  "nombre": "Partido Verde Guatemalteco",
  "afiliados": 28023,
  "color": null,
  "colorLabel": null,
  "accent": "#4A617A",
  "sg": "DELIA EMILDA BAC ALVARADO",
  "pres": null,
  "presEstado": null,
  "presAnunciado": false,
  "evento": null,
  "arranque": "2027-03",
  "decisor": "Evelyn María Quiqui Gómez",
  "decisorCargo": "secretaria de Comunicación (CEN Calidad) — verificar inscripción TSE del CEN Calidad",
  "confianza": "medio",
  "porQue": "Electa Sec. Comunicación en asamblea Verde→Calidad (09/08/2026). LPP 28/08 aún lista PV/Bac; confianza media hasta confirmación Registro.",
  "finanzas": "Luis Adely Trujillo",
  "tel": "5804-4305",
  "telAlt": null,
  "correo": "partidoverdeguatemalteco@gmail.com",
  "canal": "Correo formal a sede + llamada de seguimiento al teléfono TSE (mismo día o al día siguiente)",
  "sede": "16 calle 5-20 Oficina 2, Segundo Nivel, Interior Zona 1 Guatemala",
  "zona": "Zona 1 Ciudad de Guatemala",
  "horario": null,
  "score": "B",
  "scoreRazon": "tel+correo; CEN amplio; finanzas:Luis Adely Trujillo; coms:Evelyn María Quiqui Gómez",
  "orden": 23,
  "pitch": "Material promocional y merchandising de campaña (gorras, camisetas, banderas, lonas, stickers) con entrega rápida y precios por volumen para afiliación territorial y arranque preelectoral 2027.",
  "rank": 23,
  "dip": null,
  "alc": null,
  "deptos": null,
  "promo2023": "desconocido",
  "riesgo": "bajo",
  "sancion": "desconocido",
  "web": null,
  "fb": null,
  "ig": null,
  "x": null,
  "tiktok": null,
  "notas": "Asamblea cambió a CALIDAD (Partido Calidad) (verificar TSE)"
 },
 {
  "sig": "PC",
  "nombre": "Prosperidad Ciudadana",
  "afiliados": 27737,
  "color": null,
  "colorLabel": null,
  "accent": "#4A617A",
  "sg": "LILIAN PIEDAD GARCIA CONTRERAS",
  "pres": null,
  "presEstado": null,
  "presAnunciado": false,
  "evento": "Asamblea nacional extraordinaria (órganos permanentes) programada 16 ago 2026 (Soy502)",
  "arranque": "2027-03",
  "decisor": "LILIAN PIEDAD GARCIA CONTRERAS",
  "decisorCargo": "secretario general",
  "confianza": "bajo",
  "porQue": "único contacto oficial TSE; comando de campaña aún no publicado",
  "finanzas": null,
  "tel": "3006-5432",
  "telAlt": "3066-7427",
  "correo": "prosperidadciudadananac@gmail.com",
  "canal": "Correo formal a sede + llamada de seguimiento al teléfono TSE (mismo día o al día siguiente)",
  "sede": "14 calle 6-12 zona 1 Oficina No. 310 Edificio Valenzuela",
  "zona": "Zona 1 Ciudad de Guatemala",
  "horario": null,
  "score": "B",
  "scoreRazon": "tel+correo; web/redes",
  "orden": 24,
  "pitch": "Material promocional y merchandising de campaña (gorras, camisetas, banderas, lonas, stickers) con entrega rápida y precios por volumen para afiliación territorial y arranque preelectoral 2027.",
  "rank": 24,
  "dip": null,
  "alc": null,
  "deptos": null,
  "promo2023": "bajo",
  "riesgo": "desconocido",
  "sancion": "desconocido",
  "web": null,
  "fb": "https://www.facebook.com/prosperidad.ciudadana/",
  "ig": null,
  "x": null,
  "tiktok": null,
  "notas": null
 },
 {
  "sig": "URNG-MAIZ",
  "nombre": "Unidad Revolucionaria Nacional Guatemalteca",
  "afiliados": 25793,
  "color": "#E15D27",
  "colorLabel": "naranja",
  "accent": "#C65222",
  "sg": "CARLOS BARRIOS",
  "pres": null,
  "presEstado": null,
  "presAnunciado": false,
  "evento": "Asamblea nacional de postulación prevista (ventana oct 2026–ene 2027, TSE vía Soy502; fechas modificables)",
  "arranque": "2027-03",
  "decisor": "CARLOS BARRIOS",
  "decisorCargo": "secretario general",
  "confianza": "bajo",
  "porQue": "único contacto oficial TSE; comando de campaña aún no publicado",
  "finanzas": null,
  "tel": "22540704",
  "telAlt": "2254-9036",
  "correo": "cabalin30@gmail.com",
  "canal": "Correo formal a sede + llamada de seguimiento al teléfono TSE (mismo día o al día siguiente)",
  "sede": "12 Avenida \"B\" 6-00 Zona 2",
  "zona": "Zona 2 Ciudad de Guatemala",
  "horario": null,
  "score": "B",
  "scoreRazon": "tel+correo; web/redes",
  "orden": 25,
  "pitch": "Material promocional y merchandising de campaña (gorras, camisetas, banderas, lonas, stickers) con entrega rápida y precios por volumen para afiliación territorial y arranque preelectoral 2027.",
  "rank": 27,
  "dip": null,
  "alc": 2,
  "deptos": null,
  "promo2023": "bajo",
  "riesgo": "bajo",
  "sancion": "desconocido",
  "web": null,
  "fb": "https://www.facebook.com/urngmaiz",
  "ig": null,
  "x": null,
  "tiktok": null,
  "notas": null
 },
 {
  "sig": "XG",
  "nombre": "Xguate",
  "afiliados": 31938,
  "color": null,
  "colorLabel": null,
  "accent": "#4A617A",
  "sg": "MANUEL HAROLDO CASTILLO REYNA",
  "pres": "Edmond Mulet",
  "presEstado": "Edmond Mulet",
  "presAnunciado": true,
  "evento": "Primera Asamblea Nacional (~4 oct 2026) para elegir SG/CEN (La Hora / cobertura Mulet)",
  "arranque": "2027-03",
  "decisor": "MANUEL HAROLDO CASTILLO REYNA",
  "decisorCargo": "secretario general",
  "confianza": "bajo",
  "porQue": "único contacto oficial TSE; comando de campaña aún no publicado",
  "finanzas": null,
  "tel": "4687-3918",
  "telAlt": null,
  "correo": "xguate@xguate.gt",
  "canal": "Correo formal a sede + llamada de seguimiento al teléfono TSE (mismo día o al día siguiente)",
  "sede": "2ª. Avenida 5-05 Zona 1, Chimaltenango",
  "zona": "Zona 1 Chimaltenango",
  "horario": null,
  "score": "C",
  "scoreRazon": "tel+correo pero solo sede TSE / sin web-redes ni CEN/coms/finanzas",
  "orden": 26,
  "pitch": "Material promocional y merchandising de campaña (gorras, camisetas, banderas, lonas, stickers) con entrega rápida y precios por volumen para posicionar a Edmond Mulet y la marca del partido hacia 2027.",
  "rank": 6,
  "dip": null,
  "alc": null,
  "deptos": null,
  "promo2023": "desconocido",
  "riesgo": "bajo",
  "sancion": "desconocido",
  "web": null,
  "fb": null,
  "ig": null,
  "x": null,
  "tiktok": null,
  "notas": null
 },
 {
  "sig": "PODER",
  "nombre": "Partido De Oportunidades Y Desarrollo",
  "afiliados": 26521,
  "color": null,
  "colorLabel": null,
  "accent": "#4A617A",
  "sg": "WALFRE OSWALDO LARA MATUTE",
  "pres": "Oscar Rodolfo Castañeda",
  "presEstado": "Oscar Rodolfo Castañeda (precandidato)",
  "presAnunciado": true,
  "evento": "Asamblea (órganos) prevista 20 sep 2026 en Villa Nueva (Soy502)",
  "arranque": "2027-03",
  "decisor": "WALFRE OSWALDO LARA MATUTE",
  "decisorCargo": "secretario general",
  "confianza": "bajo",
  "porQue": "único contacto oficial TSE; comando de campaña aún no publicado",
  "finanzas": null,
  "tel": "4744-6709",
  "telAlt": "4956-2962",
  "correo": "walfrelaramatute@hotmail.com",
  "canal": "Correo formal a sede + llamada de seguimiento al teléfono TSE (mismo día o al día siguiente)",
  "sede": "10ª Avenida 12-42 Zona 1, Oficina No. 21",
  "zona": "Zona 1 Ciudad de Guatemala",
  "horario": null,
  "score": "C",
  "scoreRazon": "tel+correo pero solo sede TSE / sin web-redes ni CEN/coms/finanzas",
  "orden": 27,
  "pitch": "Material promocional y merchandising de campaña (gorras, camisetas, banderas, lonas, stickers) con entrega rápida y precios por volumen para posicionar a Oscar Rodolfo Castañeda y la marca del partido hacia 2027.",
  "rank": 26,
  "dip": null,
  "alc": null,
  "deptos": null,
  "promo2023": "bajo",
  "riesgo": "desconocido",
  "sancion": "desconocido",
  "web": null,
  "fb": null,
  "ig": null,
  "x": null,
  "tiktok": null,
  "notas": "Dick Morris asesora a Castañeda (no al partido formalmente); no contactar como jefe de compras del partido."
 },
 {
  "sig": "RETO",
  "nombre": "Partido Político Reconstrucción Total",
  "afiliados": 22371,
  "color": null,
  "colorLabel": null,
  "accent": "#4A617A",
  "sg": "JÓVITA CARRERA MORÁN",
  "pres": null,
  "presEstado": null,
  "presAnunciado": false,
  "evento": null,
  "arranque": "2027-03",
  "decisor": "JÓVITA CARRERA MORÁN",
  "decisorCargo": "secretario general",
  "confianza": "bajo",
  "porQue": "único contacto oficial TSE; comando de campaña aún no publicado",
  "finanzas": null,
  "tel": "4067-9191",
  "telAlt": null,
  "correo": "maxafre@gmail.com",
  "canal": "Correo formal a sede + llamada de seguimiento al teléfono TSE (mismo día o al día siguiente)",
  "sede": "Sexta avenida 0-60 zona 4, Gran Centro Comercial de la Zona 4, Torre Profesional 1, Oficina 710, Ciudad de Guatemala",
  "zona": "Zona 4 Ciudad de Guatemala",
  "horario": null,
  "score": "C",
  "scoreRazon": "tel+correo pero solo sede TSE / sin web-redes ni CEN/coms/finanzas",
  "orden": 28,
  "pitch": "Material promocional y merchandising de campaña (gorras, camisetas, banderas, lonas, stickers) con entrega rápida y precios por volumen para afiliación territorial y arranque preelectoral 2027.",
  "rank": 28,
  "dip": null,
  "alc": null,
  "deptos": null,
  "promo2023": "desconocido",
  "riesgo": "bajo",
  "sancion": "desconocido",
  "web": null,
  "fb": null,
  "ig": null,
  "x": null,
  "tiktok": null,
  "notas": null
 }
];
